package gui;
import java.awt.Font;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;



/**
 *
 * @author jatin
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public Category() {
        initComponents();
        tableProperties();
        getEntries();
        updateCategory.setOpaque(false);
        
        
    }
    
    void tableProperties(){
        
        TableColumn headC = table.getColumnModel().getColumn(0);
        headC.setPreferredWidth(80);
        TableColumn headC1 = table.getColumnModel().getColumn(1);
        headC1.setPreferredWidth(120);
        
        
        JTableHeader headerD = table.getTableHeader();
        headerD.setFont(new Font("Trebuchet MS", Font.BOLD, 20));
        
        
    }
    
    private void getEntries(){
        try{
            javax.swing.table.DefaultTableModel dtm =  (javax.swing.table.DefaultTableModel)table.getModel();
            
            int rc = dtm.getRowCount();
            while(rc--!=0){
                dtm.removeRow(0);
            }
            
            ResultSet rs = db.DbConnect.st.executeQuery("select * from category_info order by cID");
           
            while(rs.next()){
                
                
                Object o[] = {rs.getInt("cID"),rs.getString("category")};
                dtm.addRow(o);
                
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        updateCategory = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        deleteCategory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Category View");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        kGradientPanel1.setkGradientFocus(800);

        jPanel6.setOpaque(false);

        updateCategory.setBackground(new java.awt.Color(212, 6, 205));
        updateCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        updateCategory.setForeground(new java.awt.Color(255, 255, 255));
        updateCategory.setText("Update Selected Category");
        updateCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        updateCategory.setContentAreaFilled(false);
        updateCategory.setMaximumSize(new java.awt.Dimension(360, 55));
        updateCategory.setMinimumSize(new java.awt.Dimension(360, 55));
        updateCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCategoryActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(77, 188, 255));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add New Category");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        t.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });

        table.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setRowHeight(30);
        table.setShowGrid(true);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Category:");

        deleteCategory.setBackground(new java.awt.Color(212, 6, 205));
        deleteCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        deleteCategory.setForeground(new java.awt.Color(255, 255, 255));
        deleteCategory.setText("Delete Selected Category");
        deleteCategory.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        deleteCategory.setContentAreaFilled(false);
        deleteCategory.setMaximumSize(new java.awt.Dimension(272, 30));
        deleteCategory.setMinimumSize(new java.awt.Dimension(272, 30));
        deleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(updateCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(deleteCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(t)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(deleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {deleteCategory, updateCategory});

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        getEntries();
    }//GEN-LAST:event_formWindowClosing

    private void deleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategoryActionPerformed
        int rowID = table.getSelectedRow();

        if(rowID!=-1){

            Icon binicon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/binIcon.png"));
            int r = JOptionPane.showConfirmDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Deleting this Category will DELETE ALL TRANSACTIONS associated with it, Do You Still want to Delete ? </p></html>" , "Deletion Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, binicon);

            if(r==JOptionPane.YES_OPTION){
                String category = (String)table.getValueAt(rowID, 1);
                try{
                    

                    db.DbConnect.st.executeUpdate("delete from category_info where category = '"+category+"'");
                    db.DbConnect.st.executeUpdate("delete from spendings where category = '"+category+"'");
                    javax.swing.table.DefaultTableModel dtm =  (javax.swing.table.DefaultTableModel)table.getModel();
                    javax.swing.table.DefaultTableModel dtmo =  (javax.swing.table.DefaultTableModel)ExpenseTracker.table.getModel();
            
                    int rc = dtm.getRowCount();
                    int rct = dtmo.getRowCount();
                    db.DbConnect.st.execute("alter table category_info auto_increment = "+rc);
                    db.DbConnect.st.execute("alter table spendings auto_increment = "+rct);

                    Icon successicon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/successicon.png"));
                    JOptionPane.showMessageDialog(null,"<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Category Deleted Successfully</p></html>","Success", JOptionPane.INFORMATION_MESSAGE,successicon);
                    getEntries();
                } catch(Exception ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
    }//GEN-LAST:event_deleteCategoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String category=t.getText();
            if(!category.equals("")){

                db.DbConnect.st.executeUpdate("insert into category_info(category) values('" + category + "')");
                Icon successicon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/successicon.png"));

                JOptionPane.showMessageDialog(null,"<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Category Added Successfully</p></html>","Success", JOptionPane.INFORMATION_MESSAGE,successicon);
                getEntries();
            }else{
                Icon erroricon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/errorIcon.png"));
                JOptionPane.showMessageDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Please enter a Name</p></html>", "Warning", HEIGHT, erroricon);
            }
        }
        catch(SQLIntegrityConstraintViolationException ex){
            Icon erroricon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/errorIcon.png"));
            JOptionPane.showMessageDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Category with same name already exists</p></html>", "Warning", HEIGHT, erroricon);
        }
        catch(SQLSyntaxErrorException ex){
            Icon erroricon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/errorIcon.png"));
            JOptionPane.showMessageDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">You can't use ' or &#34; in Category Name </p></html>", "Warning", HEIGHT, erroricon);
        }
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_tActionPerformed

    private void updateCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCategoryActionPerformed

        try{
            int rowID = table.getSelectedRow();
            if(rowID!=-1){
                int id = (int)table.getValueAt(rowID, 0);
                String selectedcategory = (String)table.getValueAt(rowID, 1);
                String updatedCategory = JOptionPane.showInputDialog("<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Enter new name for this Category</p></html>");
                try{
                    if (updatedCategory!= null){

                        db.DbConnect.st.executeUpdate("update category_info set category = '"+updatedCategory+"' where cID = '"+id+"' ");
                        db.DbConnect.st.executeUpdate("update spendings set category = '"+updatedCategory+"' where category =                   '"+selectedcategory+"' ");
                        Icon successicon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/successicon.png"));

                        JOptionPane.showMessageDialog(null,"<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Category Updated Successfully</p></html>","Success", JOptionPane.INFORMATION_MESSAGE,successicon);
                    }
                    else{}
                    getEntries();
                }
                catch(SQLSyntaxErrorException ex){
            Icon erroricon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/errorIcon.png"));
            JOptionPane.showMessageDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">You can't use ' or &#34; in Category Name </p></html>", "Warning", HEIGHT, erroricon);
        }
                catch(SQLIntegrityConstraintViolationException ex){

                    Icon erroricon = new javax.swing.ImageIcon(getClass().getResource("/Extrafiles/errorIcon.png"));
                    JOptionPane.showMessageDialog(null, "<html><p style=\"color:black; font-size:18px; font-family: 'calibri'\">Category with same name already exists, Please choose a different Name.</p></html>", "Warning", HEIGHT, erroricon);
                }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_updateCategoryActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField t;
    private javax.swing.JTable table;
    private javax.swing.JButton updateCategory;
    // End of variables declaration//GEN-END:variables
}
